name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build HTML
        uses: ammaraskar/sphinx-action@0.4
      - name: Setup Pages
        uses: actions/configure-pages@v2.1.2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/_build/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
